/* Hint Cloud Data
 *
 * TODO:
 * Language Translation:
 *  - add hintclouds in DE and CZ
 *  - assemble both ENG and DE/CZ prompts
 *      - if lang = ENG, store only ENG
 *  - show preferred language prompt
 *
 */

var Facts = {
  funFacts: {
    ENG: [
      "The first use of the term digital art was in the early 1980s when the pioneering digital artist Harold Cohen created AARON, a robotic machine designed to make large drawings on sheets of paper placed on the floor.",
      "One of the earliest electronic works is 'Oscillon 40' dating from 1952. The artist, Ben Laposky, used an oscilloscope to manipulate electronic waves that appeared on the small fluorescent screen.",
      "In the early 1960s, access to computers was limited and as a result, some of the first people to use computers creatively were computer scientists or mathematicians.",
      "In the early 1970s, the Slade School of Art in  London etablished what was later called the 'Experimental and Computing Department'.",
      "Many artists who now work with computers incorporate this technology into their practice as just one tool amongst many that they may use interchangeably. Many no longer define themselves as practitioners of a specific media.",
    ],
    CZ: [
      "První použití termínu digitální umění bylo na počátku 80. let, kdy průkopnický digitální umělec Harold Cohen vytvořil AARON, robotický stroj určený k vytváření velkých kreseb na listech papíru umístěných na podlaze.",
      "Jedním z nejstarších elektronických děl je 'Oscillon 40' z roku 1952. Umělec Ben Laposky použil osciloskop k manipulaci s elektronickými vlnami, které se objevily na malé fluorescenční obrazovce.",
      "Na počátku 60. let byl přístup k počítačům omezený a v důsledku toho někteří z prvních lidí, kteří počítače kreativně používali, byli počítačoví vědci nebo matematici.",
      "Na počátku 70. let minulého století zřídila Slade School of Art v Londýně to, co bylo později nazváno 'Experimentální a výpočetní oddělení'.",
      "Mnoho umělců, kteří nyní pracují s počítači, začleňuje tuto technologii do své praxe jako jeden z mnoha nástrojů, které mohou používat zaměnitelně. Mnozí se již nedefinují jako praktikující konkrétního média.",
    ],
    DE: [
      "Die erste Verwendung des Begriffs digitale Kunst erfolgte in den frühen 1980er Jahren, als der bahnbrechende digitale Künstler Harold Cohen AARON erschuf, eine Robotermaschine, die dazu bestimmt war, große Zeichnungen auf Papierbögen zu machen, die auf dem Boden liegen.",
      "Eines der frühesten elektronischen Werke ist 'Oscillon 40' aus dem Jahr 1952. Der Künstler Ben Laposky benutzte ein Oszilloskop, um elektronische Wellen zu manipulieren, die auf dem kleinen fluoreszierenden Bildschirm erschienen.",
      "In den frühen 1960er Jahren war der Zugang zu Computern begrenzt, und infolgedessen waren einige der ersten Menschen, die Computer kreativ nutzten, Informatiker oder Mathematiker.",
      "In den frühen 1970er Jahren gründete die Slade School of Art in London das, was später als 'Experimental and Computing Department' bezeichnet wurde.",
      "Viele Künstler, die jetzt mit Computern arbeiten, integrieren diese Technologie in ihre Praxis als nur ein Werkzeug unter vielen, das sie austauschbar verwenden können. Viele definieren sich nicht mehr als Praktiker eines bestimmten Mediums.",
    ],
  },

  projectHeading: {
    ENG: "Art Generator",
    CZ: "Generátor umění",
    DE: "Kunstgenerator",
  },

  introText: {
    ENG: "From now on, anyone can be an artist!",
    CZ: "Nyní může být každý umělcem!",
    DE: "Von jetzt an, kann jeder ein Künstler sein",
  },

  introNudge: {
    ENG: "Create a new custom piece of art",
    CZ: "Vytvoř si originální, osobní umělecké dílo",
    DE: "Erstellen Sie ein ein neues eigenes Kunstwerk",
  },

  stage_names: {
    ENG: {
      medium: "Select a Medium",
      painting: [
        "Select a painting type",
        "Select painting content",
        "Select a painting setting",
        "Select an emotion",
        "Select a look or technique",
        "Select an art style",
      ],
      sculpture: [
        "Sculpture Type",
        "Sculpture Content",
        "Forms",
        "Emotions",
        "Looks",
        "Art Styles",
      ],
      photography: [
        "Photo Content",
        "Photo Setting",
        "Camera Angle",
        "Camera Settings",
        "Lighting",
        "Emotions",
      ],
    },

    CZ: {
      medium: "Vyberte médium",
      painting: [
        "Typy malby",
        "Obsah malby",
        "Prostředí malby",
        "Emoce",
        "Vzhled a technika",
        "Umělecké styly",
      ],
      sculpture: [
        "Typ sochy",
        "Obsah sochy",
        "Formy",
        "Emoce",
        "Vzhled",
        "Umělecké styly",
      ],
      photography: [
        "Obsah fotografie",
        "Prostředí fotografie",
        "Úhel",
        "Nastavení fotoaparátu",
        "Osvětlení",
        "Emoce",
      ],
    },
    DE: {
      medium: "Wählen Sie ein Medium",
      painting: [
        "Wählen Sie eine Malart",
        "Wählen Sie einen Bildinhalt",
        "Wählen Sie eine Bildkonstellation",
        "Wählen Sie eine Stimmung",
        "Wählen Sie einen Look oder Technik",
        "Wählen Sie ein Kunststil",
      ],
      sculpture: [
        "Skulptur Typ",
        "Skulptur Inhaltt",
        "Formen",
        "Emotionen",
        "Looks",
        "Kunststil",
      ],
      photography: [
        "Photoinhalt",
        "Photoeinstellung",
        "Kamerawinkel",
        "Camera Einstellungen",
        "Licht",
        "Emotionen",
      ],
    },
  },

  emotions_EN: [
    "light",
    "peaceful",
    "calm",
    "serene",
    "soothing",
    "relaxed",
    "comforting",
    "cosy",
    "tranquil",
    "quiet",
    "delicate",
    "subtle",
    "mild",
    "ethereal",
    "elegant",
    "tender",
    "soft",
    "light",
    "bright",
    "vibrant",
    "dynamic",
    "spirited",
    "vivid",
    "lively",
    "energetic",
    "colorful",
    "joyful",
    "romantic",
    "expressive",
    "rich",
    "ecstatic",
    "energized",
    "zestful",
    "passionate",
    "hot",
    "muted",
    "bleak",
    "funereal",
    "somber",
    "melancholic",
    "mournful",
    "gloomy",
    "dismal",
    "sad",
    "pale, washed-out",
    "desaturated",
    "grey",
    "dull",
    "dreary",
    "depressing",
    "weary",
    "tired",
    "dark",
    "ominous",
    "threatening",
    "haunting",
    "forbidding",
    "gloomy",
    "stormy",
    "doom",
    "apocalyptic",
    "sinister",
    "shadowy",
    "ghostly",
    "unnerving",
    "harrowing",
    "dreadful",
    "frightful",
    "shocking",
    "terror",
    "hideous",
    "ghastly",
    "terrifying",
  ],

  emotions_CZ: [
    "lehký",
    "klidný",
    "klidný",
    "klidný",
    "uklidňující",
    "uvolněný",
    "uklidňující",
    "útulný",
    "klidný",
    "tichý",
    "jemný",
    "mírný",
    "éterický",
    "elegantní",
    "něžný",
    "měkký",
    "lehký",
    "jasný",
    "živý",
    "dynamický",
    "duchovní",
    "živý",
    "energický",
    "barevný",
    "radostný",
    "romantický",
    "výrazný",
    "bohatý",
    "extatický",
    "energizovaný",
    "radostný",
    "vášnivý",
    "žhavý",
    "tlumený",
    "pochmurný",
    "pohřební",
    "smutný",
    "melancholický",
    "truchlivý",
    "chmurný",
    "pochmurný",
    "smutný",
    "bledý, sepraný",
    "desaturovaný",
    "šedý",
    "nudný",
    "ponurý",
    "depresivní",
    "unavený",
    "unavený",
    "tmavý",
    "zlověstný",
    "hrozivý",
    "strašidelný",
    "zakazující",
    "chmurný",
    "bouřlivý",
    "zkáza",
    "apokalyptický",
    "zlověstný",
    "stínový",
    "přízračný",
    "znervózňující",
    "drásající",
    "strašlivý",
    "strašný",
    "šokující",
    "děs",
    "hrozný",
    "strašlivý",
    "děsivý",
  ],

  emotions_DE: [
    "leicht",
    "friedlich",
    "ruhig",
    "gelassen",
    "beruhigend",
    "entspannt",
    "beruhigend",
    "gemütlich",
    "ruhig",
    "leise",
    "zart",
    "fein",
    "mild",
    "ätherisch",
    "elegant",
    "zart",
    "weich",
    "leicht",
    "hell",
    "lebendig",
    "dynamisch",
    "temperamentvoll",
    "lebhaft",
    "lebhaft",
    "energetisch",
    "bunt",
    "freudig",
    "romantisch",
    "ausdrucksstark",
    "reich",
    "ekstatisch",
    "energiegeladen",
    "schwungvoll",
    "leidenschaftlich",
    "heiß",
    "gedämpft",
    "trostlos",
    "beerdigt",
    "düster",
    "melancholisch",
    "traurig",
    "düster",
    "düster",
    "traurig",
    "bleich, verwaschen",
    "entsättigt",
    "grau",
    "stumpf",
    "trostlos",
    "deprimierend",
    "müde",
    "müde",
    "dunkel",
    "ominös",
    "bedrohlich",
    "eindringlich",
    "verboten",
    "düster",
    "stürmisch",
    "untergangsartig",
    "apokalyptisch",
    "finster",
    "schattenhaft",
    "gespenstisch",
    "entnervend",
    "erschütternd",
    "schrecklich",
    "schrecklich",
    "schockierend",
    "schrecklich",
    "schrecklich",
    "schrecklich",
    "erschreckend",
  ],

  structure_looks_EN: [
    "swirling",
    "organic",
    "flowing",
    "turbulent",
    "distorted",
    "uneven",
    "lush",
    "chaotic",
    "monumental",
    "rigorous",
    "imposing",
    "geometric",
    "ordered",
    "angular",
    "straight",
    "rhythmic",
    "composed",
    "unified",
    "harmonic",
    "manmade",
    "minimalist",
    "blocks",
    "robust",
    "defined",
    "ornate",
    "delicate",
    "neat",
    "precise",
    "detailed",
    "fine",
    "elaborate",
    "intricate",
    "accurate",
    "meticulous",
    "decorative",
    "random",
    "casual",
    "spontaneous",
    "uniform",
    "offhand",
    "experimental",
    "improvisational",
    "loose",
  ],

  structure_looks_CZ: [
    "točící se",
    "organický/á",
    "plující",
    "turbulentní",
    "narušený/á",
    "nepoměrný/á",
    "plný/á",
    "chaotický/á",
    "monumentální",
    "přísný/á",
    "imponující",
    "geometrický/á",
    "podle řádu",
    "hranatý/á",
    "přímý/á",
    "rytmický/á",
    "uhlazený/á",
    "sjednocený/á",
    "harmonický/á",
    "lidsky vyrobený/á",
    "minimalistický/á",
    "bloky",
    "robustní",
    "definovaný/á",
    "zdobený/á",
    "delikátní",
    "přesný/á",
    "precizní",
    "detailní",
    "jemný/á",
    "propracovaný/á",
    "intrikátní",
    "výstižný/á",
    "pečlivý/á",
    "dekorativní",
    "náhodný/á",
    "neformální",
    "spontánní",
    "uniformní",
    "zbrklý/á",
    "experimentální",
    "improvizační",
    "volný/á",
  ],

  structure_looks_DE: [
    "wirbelnd",
    "organisch",
    "fliessend",
    "turbulent",
    "verzerrt",
    "uneben",
    "ueppig",
    "chaotisch",
    "monumental",
    "rigoros",
    "imposierend",
    "geometrisch",
    "streng",
    "eckig",
    "gerade",
    "rhythmisch",
    "gefasst",
    "vereint",
    "heroisch",
    "menschengemacht",
    "minimalistisch",
    "blockig",
    "robust",
    "definiert",
    "kunstvoll",
    "empfindlich",
    "ordentlich",
    "praezis",
    "detailiert",
    "fein",
    "elaboriert",
    "verworren",
    "akkurat",
    "sorgfaeltig",
    "dekorativ",
    "zufaellig",
    "gemuetlich",
    "spontan",
    "einheitlich",
    "laessig",
    "experimentell",
    "improvisiert",
    "lose",
  ],

  looks_techniques_EN: [
    "kaleidoscopic",
    "psychedelic",
    "saturated",
    "minimalist",
    "vaporwave",
    "neon",
    "futuristic",
    "post-apocalyptic",
    "gothic",
    "fantasy",
    "cyberpunk",
    "cybernetic",
    "sci-fi",
    "steampunk",
    "memphis",
    "dieselpunk",
    "industrial",
    "afrofuturism",
    "biopunk",
    "experimental",
    "primitivist",
    "monochrome",
  ],

  looks_techniques_CZ: [
    "kaleidoscopický/á",
    "psychedelický/á",
    "saturovaný/á",
    "minimalistický/á",
    "vaporwave",
    "neonový/á",
    "futuristický/á",
    "post-apocalyptický/á",
    "gotický/á",
    "fantasy",
    "cyberpunkový/á",
    "kybernetický/á",
    "sci-fi",
    "steampunkový/á",
    "memphis",
    "dieselpunkový/á",
    "industriální",
    "afrofuturistický/á",
    "biopunkový/á",
    "experimentální",
    "primitivistický/á",
    "monochromní",
  ],

  looks_techniques_DE: [
    "kaleidoskopisch",
    "psychedelisch",
    "saturiert",
    "minimalistisch",
    "vaporwave",
    "neon",
    "futuristisch",
    "post-apocalyptisch",
    "gothic",
    "fantasy",
    "cyberpunk",
    "cybernetisch",
    "sci-fi",
    "steampunk",
    "memphis",
    "dieselpunk",
    "industrial",
    "afrofuturismus",
    "biopunk",
    "experimentell",
    "primitivistisch",
    "monochrom",
  ],

  painting_art_styles_EN: [
    "cave paintings",
    "ancient egyptian mural",
    "byzantine",
    "Renaissance",
    "Baroque",
    "Romanticism",
    "Impressionism",
    "Realism",
    "Art Nouveau",
    "Mannerism",
    "Roccoco",
    "Neoclassicism",
    "Symbolist",
    "Art deco",
    "Abstract",
    "Bauhaus",
    "Cubism",
    "Fauvism",
    "Dada",
    "Expressionism",
    "Constructivism",
    "Surrealism",
    "Abstract Expressionism",
    "Modernism",
    "religious",
    "Ottoman",
    "Pointillism",
    "Medieval",
    "Gutai",
    "Fluxus",
    "Nouveau réalisme",
    "Socialist realism",
    "Naturalism",
    "Harlem renaissance",
    "Madhubani",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Sandro Botticelli",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Georgia O'Keeffe",
    "Njideka Crosby",
    "Lucien Freud",
    "Georges Seurat",
    "Mary Cassatt",
    "Artemisia Gentileschi",
    "Berthe Morisot",
    "Helen Frankenthaler",
    "Yayoi Kusama",
    "Fra' Angelico",
  ],

  painting_art_styles_CZ: [
    "jeskynní malby",
    "egyptského murálu",
    "Byzance",
    "Renezance",
    "Baroka",
    "Romantismu",
    "Impresionismu",
    "Realismu",
    "Art Nouveau",
    "Manerismu",
    "Rokoka",
    "Neoklasicismu",
    "Symbolismu",
    "Art deco",
    "Abstrakce",
    "Bauhaus",
    "Kubismu",
    "Fauvismu",
    "Dada",
    "Expresionismu",
    "Konstruktivismu",
    "Surealismu",
    "Abstraktního Expresionismu",
    "Modernismu",
    "Náboženském",
    "Otomanském",
    "Pointilismu",
    "Středověku",
    "Gutai",
    "Fluxus",
    "Nového realismu",
    "Socialistického realismu",
    "Naturalismu",
    "Harlemské renezance",
    "Madhubani",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Sandro Botticelli",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Georgia O'Keeffe",
    "Njideka Crosby",
    "Lucien Freud",
    "Georges Seurat",
    "Mary Cassatt",
    "Artemisia Gentileschi",
    "Berthe Morisot",
    "Helen Frankenthaler",
    "Yayoi Kusama",
    "Fra' Angelico",
  ],

  painting_art_styles_DE: [
    "Hoehlenmalerei",
    "altaegyptische Wandmalerei",
    "byzantisch",
    "Renaissance",
    "Barock",
    "Romantik",
    "Impressionismus",
    "Realismus",
    "Art Nouveau",
    "Manierismus",
    "Rokoko",
    "Neoklassizismus",
    "Symbolismus",
    "Art deco",
    "Abstrakt",
    "Bauhaus",
    "Kubismus",
    "Fauvismus",
    "Dada",
    "Expressionismus",
    "Konstruktivismus",
    "Surrealismus",
    "Abstrakter Expressionismus",
    "Modernismus",
    "religiös",
    "Osmanisch",
    "Pointillismus",
    "mittelalterlich",
    "Gutai",
    "Fluxus",
    "Nouveau réalisme",
    "Socialistischer Realismus",
    "Naturalismus",
    "Harlem renaissance",
    "Madhubani",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Sandro Botticelli",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Georgia O'Keeffe",
    "Njideka Crosby",
    "Lucien Freud",
    "Georges Seurat",
    "Mary Cassatt",
    "Artemisia Gentileschi",
    "Berthe Morisot",
    "Helen Frankenthaler",
    "Yayoi Kusama",
    "Fra' Angelico",
  ],

  sculpture_art_styles_EN: [
    "egyptian",
    "byzantine",
    "Renaissance",
    "Baroque",
    "Romanticism",
    "Impressionism",
    "Realism",
    "Art Nouveau",
    "Mannerism",
    "Roccoco",
    "Neoclassicism",
    "Symbolist",
    "Art deco",
    "Abstract",
    "Bauhaus",
    "Cubism",
    "Fauvism",
    "Dada",
    "Expressionism",
    "Constructivism",
    "Surrealism",
    "Abstract Expressionism",
    "Modernism",
    "religious",
    "Ottoman",
    "Pointillism",
    "Medieval",
    "Gutai",
    "Fluxus",
    "Nouveau réalisme",
    "Socialist realism",
    "Naturalism",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Berthe Morisot",
    "Yayoi Kusama",
    "Matisse",
    "Renoir",
    "Giacometti",
    "Henry Moore",
    "Antony Gormley",
  ],

  sculpture_art_styles_CZ: [
    "egyptském",
    "Byzance",
    "Renezance",
    "Baroka",
    "Romantismu",
    "Impresionismu",
    "Realismu",
    "Art Nouveau",
    "Manerismu",
    "Rokoka",
    "Neoklasicismu",
    "Symbolismu",
    "Art deco",
    "Abstrakce",
    "Bauhaus",
    "Kubismu",
    "Fauvismu",
    "Dada",
    "Expresionismu",
    "Konstruktivismu",
    "Surealismu",
    "Abstraktního Expresionismu",
    "Modernismu",
    "Náboženském",
    "Otomanském",
    "Pointilismu",
    "Středověku",
    "Gutai",
    "Fluxus",
    "Nového realismu",
    "Socialistického realismu",
    "Naturalismu",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Berthe Morisot",
    "Yayoi Kusama",
    "Matisse",
    "Renoir",
    "Giacometti",
    "Henry Moore",
    "Antony Gormley",
  ],

  sculpture_art_styles_DE: [
    "aegyptisch",
    "byzantinisch",
    "Renaissance",
    "Barock",
    "Romantik",
    "Impressionismus",
    "Realismus",
    "Art Nouveau",
    "Manierismus",
    "Rokoko",
    "Neoklassizismus",
    "Symbolismus",
    "Art deco",
    "Abstrakt",
    "Bauhaus",
    "Kubismus",
    "Fauvismus",
    "Dada",
    "Expressionismus",
    "Konstruktivismus",
    "Surrealismus",
    "Abstrakter Expressionismus",
    "Modernismus",
    "religioes",
    "Osmanisch",
    "Pointillismus",
    "mittelalterlich",
    "Gutai",
    "Fluxus",
    "Nouveau réalisme",
    "Sozialistischer Realismus",
    "Naturalismus",

    "Pablo Picasso",
    "Salvador Dali",
    "Keith Haring",
    "Vincent van Gogh",
    "Joan Miro",
    "Francis Bacon",
    "Tanguy",
    "Claude Monet",
    "Paul Cezanne",
    "Auguste Renoir",
    "Félix Vallotton",
    "Wassily Kandinsky",
    "Yves Klein",
    "Basquiat",
    "Frida Kahlo",
    "Berthe Morisot",
    "Yayoi Kusama",
    "Matisse",
    "Renoir",
    "Giacometti",
    "Henry Moore",
    "Antony Gormley",
  ],
  //painting
  //CZ preklady sklonene ve spravnem tvaru: Olejomalba 'divokych ptaku' 'v parku'  (sklonovani se meni podle predchoziho rodu!)
  //DE translate and add to hint cloud with prepositions: Oil painting 'of flying birds' 'in a park'
  painting_types_EN: [
    "crayon",
    "child drawing",
    "acrylic on canvas",
    "watercolor",
    "oil painting",
    "coloured pencil",
    "chinese watercolor",
    "pastels",
    "airbrush",
    "photocollage",
    "vector art",
    "digital art",
    "pencil drawing",
    "pencil sketch",
    "woodcut",
    "charcoal sketch",
    "cartoon",
    "animation",
    "comic style",
    "etching",
    "mural",
    "blueprint",
    "botanical illustration",
    "anatomical illustration",
    "map",
    "scientific diagram",
    "voroni diagram",
    "pixel art",
  ],

  painting_types_CZ: [
    "pastelová malba",
    "dětská kresba",
    "akryl na plátně",
    "akvarel",
    "olejomalba",
    "malba barevnou tužkou",
    "čínský akvarel",
    "pastelová malba",
    "airbrush",
    "fotokoláž",
    "vektorové umění",
    "digitální umění",
    "kresba tužkou",
    "náčrt tužkou",
    "dřevořez",
    "náčrt uhlem",
    "karikatura",
    "animace",
    "komiksový styl",
    "lept",
    "nástěnná malba",
    "modrotisk",
    "botanická ilustrace",
    "anatomická ilustrace",
    "mapa",
    "vědecký diagram",
    "voroni diagram",
    "pixelové umění",
  ],

  painting_types_DE: [
    "Kreide",
    "Kinderzeichnung",
    "Acryl auf Leinwand",
    "Aquarell",
    "Ölmalerei",
    "Buntstift",
    "chinesisches Aquarell",
    "Pastelle",
    "Airbrush",
    "Fotocollage",
    "Vektorgrafiken",
    "digitale Kunst",
    "Bleistiftzeichnung",
    "Bleistiftskizze",
    "Holzschnitt",
    "Kohlezeichnung",
    "Cartoon",
    "Animation",
    "Comic-Stil",
    "Radierung",
    "Wandbild",
    "Blaupause",
    "botanische Illustration",
    "anatomische Illustration",
    "Karte",
    "wissenschaftliches Diagramm",
    "Voroni-Diagramm",
    "Pixelkunst",
  ],

  painting_content_EN: [
    "the landscape of mars",
    "a judge",
    "the still life of fruit",
    "an orange elephant",
    "an old-fashioned greenhouse",
    "a vintage can of pickles",
    "the tower of Babel",
    "a civilization",
    "an alien plant",
    "electric sheep",
    "a bouquet of flowers",
    "a family of dolphins",
    "friends with hats",
    "the godess of Love",
    "a luminous lamp",
    "a burning cottage",
    "a red folding chair",
    "a giant spiderweb",
    "an infinite bridge",
    "a farming peasant",
    "a hunting dog",
    "particles of dust",
    "a prehistoric fern",
    "an ornate teapot",
    "burning candles",
    "all dimensions",
    "a hot air baloon",
    "a garden party",
    "a swimming figure",
    "passionate discussants",
    "a fairy tea-party",
    "a sandwich",
  ],

  painting_content_CZ: [
    "krajiny Marsu",
    "portrétu soudce",
    "zátiší ovoce",
    "oranžového slona",
    "staromódního skleníku",
    "sklenice okurek",
    "Babylonské věže",
    "civilizace",
    "mimozemské rostliny",
    "elektrické ovce",
    "kytice květin",
    "zelené rodiny delfínů",
    "přátel s klobouky",
    "bohyně lásky",
    "zážící lampy",
    "hořící chalupy",
    "červené židle",
    "obří pavučiny",
    "nekonečného mostu",
    "hospodařícího poddaného",
    "loveckého psa",
    "částic prachu",
    "pravěké kapradiny",
    "zdobené konvice",
    "hořících svíček",
    "všech dimenzí",
    "horkovzdušného balónu",
    "zahradní slavnosti",
    "plovoucí figury",
    "vášnivé diskuze",
    "čajového dýchánku víl",
    "obloženého chleba",
  ],

  painting_content_DE: [
    "Die Landschaft vom Mars",
    "Ein Richter",
    "ein Stillleben von Früchten",
    "Ein orangefarbener Elefant",
    "ein altmodisches Gewächshaus",
    "eine altmodische Dose Gurken",
    "der Turm zu Babel",
    "Eine Zivilisation",
    "eine fremde Pflanze",
    "elektrische Schafe",
    "ein Blumenstrauß",
    "eine Delfinfamilie",
    "Freunde mit Hüten",
    "the Goettin der Liebe",
    "eine helle Lampe",
    "eine brennende Hütte",
    "ein roter Klappstuhl",
    "ein riesiges Spinnennetz",
    "eine unendliche Brücke",
    "ein ackernder Landwirt",
    "ein jagender Hund",
    "Staubpartikel",
    "ein urzeitlicher Farn",
    "eine prunkvolle Teekanne",
    "brennende Kernzen",
    "alle Dimensionen",
    "ein Heissluftballon",
    "eine Gartenparty",
    "eine schwimmende Figur",
    "leidenschaftliche Diskussionen",
    "eine Feen Tee-Party",
    "ein Sandwich",
  ],

  painting_setting_EN: [
    "during a sunset",
    "in a poppy field",
    "in the French countryside",
    "by the sea",
    "during the end of the world",
    "before the storm",
    "in the poolclub",
    "underwater",
    "in a stadium",
    "in the centre of the universe",
    "in the middle of the ocean",
    "in the middle of the desert",
    "nowhere",
    "in a lush garden",
    "among the stars",
    "in front of Taj Mahal",
    "in the savanah",
    "at an oasis",
    "in a forest",
    "next to a lake",
    "by the sea",
    "on a corn field",
    "in a music studio",
    "on top of a mountain",
    "on a deserted island",
    "inside a laboratory",
    "inside an art atelier",
    "in a dark alley",
    "on the roof",
    "inside a cup",
    "on a train",
    "on the North Pole",
    "inside a black hole",
    "on planet Mars",
    "everywhere",
    "on a chaise longue",
    "in the afterlife",
  ],

  painting_setting_CZ: [
    "při západu slunce",
    "v makovém poli",
    "na francouzském venkově",
    "u moře",
    "na konci světa",
    "před bouří",
    "v klubu u bazénu",
    "pod vodou",
    "na stadionu",
    "uprostřed vesmíru",
    "uprostřed oceánu",
    "uprostřed pouště",
    "nikde",
    "ve svěží zahradě",
    "mezi hvězdami",
    "před Tádž Mahalem",
    "v savaně",
    "v oáze",
    "v lese",
    "u jezera",
    "u moře",
    "na kukuřičném poli",
    "v hudebním studiu",
    "na vrcholu hory",
    "na opuštěném ostrově",
    "v laboratoři",
    "v uměleckém ateliéru",
    "v temné uličce",
    "na střeše",
    "v hrníčku",
    "ve vlaku",
    "na Severním Pólu",
    "v černé díře",
    "na Marsu",
    "všude",
    "na lehátku",
    "v posmrtném životě",
  ],

  painting_setting_DE: [
    "während eines Sonnenuntergangs",
    "in einem Mohnfeld",
    "in der französischen Landschaft",
    "am Meer",
    "während de Ende der Welt",
    "vor dem Sturm",
    "im Poolclub",
    "unter Wasser",
    "in einem Stadion",
    "im Zentrum des Universums",
    "mitten im Ozean",
    "mitten in der Wüste",
    " nirgendwo",
    "in einem üppigen Garten",
    "unter den Sternen",
    "vor dem Taj Mahal",
    "in der Savanne",
    "in einer Oase",
    "in einem Wald",
    "neben einem See",
    "am Meer",
    "auf einem Maisfeld",
    "in eine Musikstudio",
    "auf einem Berg",
    "afuf einer verlassenen Wüste",
    "in einem Labor",
    "in einem Kunstatelier",
    "in einer dunklen Gasse",
    "Auf dem Dach",
    "in der Tasse",
    "auf einem Zug",
    "auf dem Nordpol",
    "in einem schwarzen Loch",
    "auf Planeten Mars'",
    "ueberall",
    "auf einer Chaiselongue",
    "im  Jenseits",
  ],

  // sculpture
  //CZ preklady sklonene ve spravnem tvaru: 'Bronzova' socha 'divokych ptaku' 'v parku'
  //DE translate and add to hint cloud with prepositions: Goldskulptur 'of flying birds' 'in a park'
  sculpture_types_EN: [
    "bronze",
    "marble",
    "terracota",
    "jade",
    "gold",
    "silver",
    "ice carving",
    "plastic",
    "fiberglass",
    "plant",
    "sand",
    "butter",
    "wood",
    "glass",
    "stone",
    "metal",
    "ceramic",
    "clay",
    "wax",
    "rubber",
    "plaster",
    "ivory",
    "fabric",
  ],

  sculpture_types_CZ: [
    "bronzová",
    "mramorová",
    "terakotová",
    "nefritová",
    "zlatá",
    "stříbrná",
    "ledová",
    "plastová",
    "laminátová",
    "rostlinná",
    "písečná",
    "máslová",
    "dřevěná",
    "skleněná",
    "kamenná",
    "železná",
    "keramická",
    "hliněná",
    "vosková",
    "gumová",
    "sádrová",
    "slonovinová",
    "textilní",
  ],

  sculpture_types_DE: [
    "Bronze",
    "Marmor",
    "Terrakotta",
    "Jade",
    "Gold",
    "Silber",
    "Eisschnitzen",
    "Plastik",
    "Glasfaser",
    "Pflanze",
    "Sand",
    "Butter",
    "Holz",
    "Glass",
    "Stein",
    "Metall",
    "Keramik",
    "Ton",
    "Wachs",
    "Gummi",
    "Gips",
    "Elfenbein",
    "Textil",
  ],
  sculpture_content_EN: [
    "warriors awaiting the battle",
    "cup of eternal life",
    "t-rex with long arms",
    "a judge",
    "the still life of fruit",
    "an orange elephant",
    "an old-fashioned greenhouse",
    "a vintage can of pickles",
    "the tower of Babel",
    "a civilization",
    "an alien plant",
    "electric sheep",
    "a bouquet of flowers",
    "a family of dolphins",
    "friends with hats",
    "the godess of Love",
    "a luminous lamp",
    "a burning cottage",
    "a red folding chair",
    "a giant spiderweb",
    "an infinite bridge",
    "a farming peasant",
    "a hunting dog",
    "particles of dust",
    "a prehistoric fern",
    "an ornate teapot",
    "burning candles",
    "all dimensions",
    "a hot air baloon",
    "a garden party",
    "a swimming figure",
    "passionate discussants",
    "a fairy tea-party",
    "a sandwich",
  ],

  sculpture_content_CZ: [
    "bojovníků očekávající bitvu",
    "kalichu věčného života",
    "t-rexe s dlouhýma rukama",
    "portrétu soudce",
    "zátiší ovoce",
    "oranžového slona",
    "staromódního skleníku",
    "sklenice okurek",
    "Babylonské věže",
    "civilizace",
    "mimozemské rostliny",
    "elektrické ovce",
    "kytice květin",
    "zelené rodiny delfínů",
    "přátel s klobouky",
    "bohyně lásky",
    "zážící lampy",
    "hořící chalupy",
    "červené židle",
    "obří pavučiny",
    "nekonečného mostu",
    "hospodařícího poddaného",
    "loveckého psa",
    "částic prachu",
    "pravěké kapradiny",
    "zdobené konvice",
    "hořících svíček",
    "všech dimenzí",
    "horkovzdušného balónu",
    "zahradní slavnosti",
    "plovoucí figury",
    "vášnivé diskuze",
    "čajového dýchánku víl",
    "obloženého chleba",
  ],

  sculpture_content_DE: [
    "Krieger die auf die Schlacht warten",
    "Kelch des unendlichen Lebens",
    "t-rex mit kurzen Beinen und langen Armen",
    "ein Richter",
    "tein Fruchtstilleben",
    "aei orangerne Elefant",
    "ein altmodisches Gewächshaus",
    "eine alte Dose mit Essiggurken",
    "der Turm von Babel",
    "eine Zivilisation",
    "eine außerirdische Pflanze",
    "elektrische Schafe",
    "ein Blumenstrauß",
    "eine Familie von Delphinen",
    "Freunde mit Hüten",
    "die Göttin der Liebe",
    "eine leuchtende Lampe",
    " eine brennende Hütte",
    "ein roter Klappstuhl",
    "ein riesiges Spinnennetz",
    "eine unendliche Brücke",
    "ein bäuerlicher Bauer",
    "ein Jagdhund",
    "Staubteilchen",
    "ein prähistorischer Farn",
    "eine verzierte Teekanne",
    "brennende Kerzen",
    "alle Dimensionen",
    "ein Heißluftballon",
    "eine Gartenparty",
    "eine schwimmende Figur",
    "leidenschaftliche Diskutanten",
    "eine feenhafte Teeparty",
    "ein Sandwich",
  ],

  sculpture_techniques_EN: [
    "carved",
    "modeled",
    "cast",
    "wrought",
    "welded",
    "sewn",
    "assembled",
    "shaped",
    "combined",
    "kinetic",
  ],

  sculpture_techniques_CZ: [
    "vyřezaná",
    "vymodelovaná",
    "z formy",
    "tepaná",
    "svářená",
    "sešitá",
    "složená",
    "vytvarovaná",
    "kombinovaná",
    "kinetická",
  ],

  sculpture_techniques_DE: [
    "geschnitzt",
    "modeliert",
    "gips",
    "gehaemmert",
    "geschweisst",
    "Genaeht",
    "Zusammengestellt",
    "Geformt",
    "Kombiniert",
    "kinetisch",
  ],

  sculpture_forms_EN: [
    "lit from above",
    "smooth texture",
    "rough texture",
    "large scale",
    "miniature",
    "lit from below",
    "in darkness",
    "life-size",
    "outdoor",
    "hanging",
    "displayed",
  ],

  sculpture_forms_CZ: [
    "nasvícená shora",
    "hladká textura",
    "hrubá textura",
    "velký rozměr",
    "miniatura",
    "nasvícená ze spoda",
    "ve tmě",
    "v živé velikosti",
    "venku",
    "visící",
    "vystavená",
  ],

  sculpture_forms_DE: [
    "von oben beleuchtet",
    "Glatte Textur",
    "raue Textur",
    "Grossformatig",
    "Kleinformatig",
    "von unten beleuchtet",
    "in dunkelheit",
    "lebensgross",
    "Im freien",
    "haengend",
    "ausgestellt",
  ],

  //photography
  //CZ preklady sklonene ve spravnem tvaru: Fotografie 'divokych ptaku' 'v parku'
  //DE translate and add to hint cloud with prepositions: Ein Foto ‘von’ fliegenden Voegeln’ ‘in einem Park’

  photo_content_EN: [
    "flying birds",
    "wild animals",
    "waterfalls",
    "exterior of a family house",
    "ministry of truth",
    "warriors awaiting the battle",
    "cup of eternal life",
    "t-rex with long arms",
    "a judge",
    "the still life of fruit",
    "an orange elephant",
    "an old-fashioned greenhouse",
    "a vintage can of pickles",
    "the tower of Babel",
    "a civilization",
    "an alien plant",
    "electric sheep",
    "a bouquet of flowers",
    "a family of dolphins",
    "friends with hats",
    "the godess of Love",
    "a luminous lamp",
    "a burning cottage",
    "a red folding chair",
    "a giant spiderweb",
    "an infinite bridge",
    "a farming peasant",
    "a hunting dog",
    "particles of dust",
    "a prehistoric fern",
    "an ornate teapot",
    "burning candles",
    "all dimensions",
    "a hot air baloon",
    "a garden party",
    "a swimming figure",
    "passionate discussants",
    "a fairy tea-party",
    "a sandwich",
  ],

  photo_content_CZ: [
    "létajících ptáků",
    "divoké zvěře",
    "vodopádů",
    "rodinného domu",
    "ministerstva pravdy",
    "bojovníků očekávající bitvu",
    "kalichu věčného života",
    "t-rexe s dlouhýma rukama",
    "portrétu soudce",
    "zátiší ovoce",
    "oranžového slona",
    "staromódního skleníku",
    "sklenice okurek",
    "Babylonské věže",
    "civilizace",
    "mimozemské rostliny",
    "elektrické ovce",
    "kytice květin",
    "zelené rodiny delfínů",
    "přátel s klobouky",
    "bohyně lásky",
    "zážící lampy",
    "hořící chalupy",
    "červené židle",
    "obří pavučiny",
    "nekonečného mostu",
    "hospodařícího poddaného",
    "loveckého psa",
    "částic prachu",
    "pravěké kapradiny",
    "zdobené konvice",
    "hořících svíček",
    "všech dimenzí",
    "horkovzdušného balónu",
    "zahradní slavnosti",
    "plovoucí figury",
    "vášnivé diskuze",
    "čajového dýchánku víl",
    "obloženého chleba",
  ],

  photo_content_DE: [
    "fliegende Vögel",
    "wilde Tiere",
    "Wasserfälle",
    "ein Familienhaus",
    "Ministerium der Wahrheit",
    "Krieger, die auf die Schlacht warten",
    "Kelch des ewigen Lebens",
    "T-Rex mit langen Armen",
    "ein Richter",
    "das stille Leben der Früchte",
    "ein orangefarbener Elefant",
    "ein altmodisches Gewächshaus",
    "eine alte Konservendose mit Gurken",
    "der Turm von Babel",
    "eine Zivilisation",
    "eine außerirdische Pflanze",
    "elektrische Schafe",
    "ein Blumenstrauß",
    "eine Familie von Delphinen",
    "Freunde mit Hüten",
    "die Göttin der Liebe",
    "eine leuchtende Lampe",
    "ein brennendes Häuschen",
    "ein roter Klappstuhl",
    "ein riesiges Spinnennetz",
    "eine unendliche Brücke",
    "ein bäuerlicher Bauer",
    "ein Jagdhund",
    "Staubteilchen",
    "ein prähistorischer Farn",
    "eine verzierte Teekanne",
    "brennende Kerzen",
    "alle Dimensionen",
    "ein Heißluftballon",
    "eine Gartenparty",
    "eine schwimmende Figur",
    "leidenschaftliche Diskutanten",
    "eine feenhafte Teeparty",
    "ein Sandwich",
  ],

  photo_setting_EN: [
    "in the savanna",
    "on a city square",
    "in London",
    "on a staircase",
    "during a sunset",
    "in a poppy field",
    "in the French countryside",
    "by the sea",
    "during the end of the world",
    "before the storm",
    "in the poolclub",
    "underwater",
    "in a stadium",
    "in the centre of the universe",
    "in the middle of the ocean",
    "in the middle of the desert",
    "nowhere",
    "in a lush garden",
    "among the stars",
    "in front of Taj Mahal",
    "in the savanah",
    "at an oasis",
    "in a forest",
    "next to a lake",
    "by the sea",
    "on a corn field",
    "in a music studio",
    "on top of a mountain",
    "on a deserted island",
    "inside a laboratory",
    "inside an art atelier",
    "in a dark alley",
    "on the roof",
    "inside a cup",
    "on a train",
    "on the North Pole",
    "inside a black hole",
    "on planet Mars",
    "everywhere",
    "on a chaise longue",
    "in the afterlife",
  ],

  photo_setting_CZ: [
    "v savaně",
    "na náměstí",
    "v Londýně",
    "na schodišti",
    "při západu slunce",
    "v makovém poli",
    "na francouzském venkově",
    "u moře",
    "na konci světa",
    "před bouří",
    "v klubu u bazénu",
    "pod vodou",
    "na stadionu",
    "uprostřed vesmíru",
    "uprostřed oceánu",
    "uprostřed pouště",
    "nikde",
    "ve svěží zahradě",
    "mezi hvězdami",
    "před Tádž Mahalem",
    "v savaně",
    "v oáze",
    "v lese",
    "u jezera",
    "u moře",
    "na kukuřičném poli",
    "v hudebním studiu",
    "na vrcholu hory",
    "na opuštěném ostrově",
    "v laboratoři",
    "v uměleckém ateliéru",
    "v temné uličce",
    "na střeše",
    "v hrníčku",
    "ve vlaku",
    "na Severním Pólu",
    "v černé díře",
    "na Marsu",
    "všude",
    "na lehátku",
    "v posmrtném životě",
  ],

  photo_setting_DE: [
    "in der Savanne",
    "auf einem Stadtplatz",
    "in London",
    "auf einer Treppe",
    "während eines Sonnenuntergangs",
    "in einem Mohnfeld",
    "auf dem Lande in Frankreich",
    "am Meer",
    "während des Weltuntergangs",
    "vor dem Sturm",
    "im Poolclub",
    "unter Wasser",
    "in einem Stadion",
    "im Zentrum des Universums",
    "in der Mitte des Ozeans",
    "mitten in der Wüste",
    "nirgendwo",
    "in einem üppigen Garten",
    "zwischen den Sternen",
    "vor dem Taj Mahal",
    "in der Savanne",
    "in einer Oase",
    "in einem Wald",
    "neben einem See",
    "am Meer",
    "auf einem Maisfeld",
    "in einem Musikstudio",
    "auf dem Gipfel eines Berges",
    "auf einer einsamen Insel",
    "im Inneren eines Labors",
    "in einem Kunstatelier",
    "in einer dunklen Gasse",
    "auf dem Dach",
    "in einer Tasse",
    "in einem Zug",
    "am Nordpol",
    "im Inneren eines schwarzen Lochs",
    "auf dem Planeten Mars",
    "überall",
    "auf einer Chaise Longue",
    "im Jenseits",
  ],

  camera_angles_EN: [
    "extreme close-up",
    "close-up",
    "medium-shot",
    "long-shot",
    "wide-shot",
    "overhead view",
    "low angle",
    "aerial view",
    "tilted frame",
  ],

  camera_angles_CZ: [
    "velmi zblízka",
    "zblízka",
    "střední záběr",
    "široký záběr",
    "velmi široký záběr",
    "pohled shora",
    "nízký úhel",
    "ptačí pohled",
    "natočený rám",
  ],

  camera_angles_DE: [
    "extreme Nahaufnahme",
    "Nahaufnahme",
    "mittelgroße Aufnahme",
    "Weitschuss",
    "Weitwinkel",
    "Draufsicht",
    "niedriger Winkel",
    "Luftaufnahme",
    "Schrägaufnahme",
  ],

  camera_settings_EN: [
    "fast shutter speed",
    "slow shutter speed",
    "tilt shift photo",
    "motion blur",
    "telephoto lens",
    "deep depth of field",
    "macro lens",
    "panoramic",
    "super-wide",
    "fish-eye lens",
    "kodachrome",
    "polaroid",
    "double exposure",
    "daguerrotype",
    "disposable camera",
    "CCTV",
    "infrared",
    "redscale",
    "black and white",
  ],

  camera_settings_CZ: [
    "rychlá spošť",
    "pomalá spoušť",
    "tilt shift",
    "rozmazání pohybu",
    "teleobjektiv",
    "hluboká hloubka ostrosti",
    "macro objektiv",
    "panorama",
    "širokoúhlý",
    "objektiv rybí oko",
    "kodachrome",
    "polaroid",
    "dvojtá expozice",
    "daguerrotypie",
    "jednorázový foťák",
    "kamerový záznam",
    "infra-červený",
    "červená stupnice",
    "černobílý",
  ],

  camera_settings_DE: [
    "Kurze Beleuchtungszeit",
    "Lange Beleuchtungszeit",
    "tilt shift Foto",
    "motion blur",
    "telephoto Objektiv",
    "Grosse Tiefenschaerfe",
    "makro Objektiv",
    "panorama",
    "super-weitwinkel",
    "Fish-eye Objektiv",
    "Kodachrome",
    "polaroid",
    "Dopppelbeleuchtung",
    "Daguerrotyp",
    "Wegwerfkamera",
    "CCTV",
    "infrarot",
    "rotskala",
    "Schwarzweiss",
  ],

  lighting_EN: [
    "golden hour",
    "blue hour",
    "midday",
    "overcast",
    "sunny day",
    "rainy weather",
    "warm lighting",
    "flash photography",
    "studio lighting",
    "colored lights",
  ],

  lighting_CZ: [
    "zlatá hodinka",
    "modrá hodinka",
    "poledne",
    "zataženo",
    "slunný den",
    "deštivo",
    "teplé osvětlení",
    "fotografie s bleskem",
    "studiové nasvícení",
    "barevná světla",
  ],

  lighting_DE: [
    "Goldene Stunde",
    "blaue Stunde",
    "Mittag",
    "bewölkt",
    "sonniger Tag",
    "regnerisches Wetter",
    "warme Beleuchtung",
    "Blitzlichtfotografie",
    "Studiobeleuchtung",
    "farbiges Licht",
  ],
};

var Prompts = {
  ENG: {
    medium:
      "The first decision every artist has to make is choosing a medium: what kind of artwork will it be?",
    painting: {
      //lookup holds the hint cloud variable for each stage ordered by stage id
      lookup: [
        "painting_types_EN",
        "painting_content_EN",
        "painting_setting_EN",
        "emotions_EN",
        "looks_techniques_EN",
        "painting_art_styles_EN",
      ],
      //holds the guiding prompt for each dialogue stage named by stage id (such that it can be called as prompt[stage])
      1: [
        "Let's get more specific. There are endless possibilities of what to do on a canvas, which one will it be?",
      ],
      2: [
        "Once we know how to approach the artwork, we can start filling it in. Go ahead, dream away:",
      ],
      3: [
        "We know what we are focusing on, but what about everything all around?",
      ],
      4: [
        "What will your artwork radiate? Think of emotions and energies you would want to convey through your artwork!",
      ],
      5: [
        "We are getting close. There are endless styles in the world of art. Will you choose to follow one?",
      ],
      6: [
        "Most of us will be driven by outer inspiration, which often takes shape in a person or a group. Perhaps you will want to finish you artwork off in the style of…",
      ],
    },
    sculpture: {
      lookup: [
        "sculpture_types_EN",
        "sculpture_content_EN",
        "sculpture_forms_EN",
        "emotions_EN",
        "structure_looks_EN",
        "sculpture_art_styles_EN",
      ],
      1: [
        "Let's get more specific. You are working with space and matter, molding it into a desired structure and shape. I have a broad selection of possible paths on hand, all you have to do is pick one!",
      ],
      2: [
        "Think of things, characters - truly anything. There are practically no limitations to what you can depict. Go ahead, dream away:",
      ],
      3: [
        "Sculptures are 3D physical objects that work with the space around them. The way they work to blend in or stick out will result in a completely different reading of the sculpture!",
      ],
      4: [
        "Now that we know what is in the artwork, the shape that it will have, we also need to know what kind of energy will this sculpture radiate.",
      ],
      5: [
        "We are getting close. There are endless styles in the world of art - these either help bring out the visuality of your scene, or better communicate the desired message.",
      ],
      6: [
        "Most of us will be driven by outer inspiration, which often takes shape in a person or a group. Perhaps you will want to finish you artwork off in the style of…",
      ],
    },
    photography: {
      lookup: [
        "photo_content_EN",
        "photo_setting_EN",
        "camera_angles_EN",
        "camera_settings_EN",
        "lighting_EN",
        "emotions_EN",
      ],
      1: [
        "Let's start thinking of the content and arrangement. Think of things, characters - truly anything. Go ahead, dream away:",
      ],
      2: [
        "We know what we are focusing on, but what about everything all around?",
      ],
      3: [
        "Photography is all about perspective. Imagine yourself in relation to the object with your intention in mind!",
      ],
      4: [
        "Every camera has some settings that can be manipulated. These will all drastically alter the final result of our photograph!",
      ],
      5: [
        "Lighting is a crucial part of photography, for all photography functions on reflected light hitting the lens of the camera.",
      ],
      6: [
        "There is always something that the artists wants to communicate. This is often an emotion or feeling, but can also be just an intention such as exploration.",
      ],
    },
  },
  CZ: {
    medium:
      "První rozhodnutí, které musí každý umělec udělat, je vybrat si médium: jaký druh uměleckého díla to bude? Každá volba má svá specifika a zavede vás trochu jinou kreativní cestou. Která z nich je vaše povolání?",
    painting: {
      //lookup holds the hint cloud variable for each stage ordered by stage id
      lookup: [
        "painting_types_CZ",
        "painting_content_CZ",
        "painting_setting_CZ",
        "emotions_CZ",
        "looks_techniques_CZ",
        "painting_art_styles_CZ",
      ],
      //holds the guiding prompt for each dialogue stage named by stage id (such that it can be called as prompt[stage])
      1: [
        "Buďme konkrétnější. Možností, co na plátně dělat, je nepřeberné množství. Můžete dát přednost výrazným barvám olejové barvy nebo jemnějšímu pojetí kresby tužkou. Technické náčrty a mozaiky však nejsou mimo hru! Každé médium má své kouzlo a všechny jsou vám k dispozici. Co to bude?",
      ],
      2: [
        "Jakmile víme, jak k uměleckému dílu přistupovat, můžeme je začít vyplňovat. Myslete na věci, postavy - opravdu cokoli.",
      ],
      3: [
        "Víme, na co se zaměřujeme, ale co všechno kolem. Kde se tato scéna odehrává? Existuje vůbec nějaké prostředí?",
      ],
      4: [
        "Teď, když víme, co je v díle, potřebujeme také vědět, jak to bude vyobrazeno. Přemýšlejte o emocích a energiích, které byste chtěli svým dílem zprostředkovat!",
      ],
      5: [
        "Ve světě umění existuje nepřeberné množství stylů – ty buď pomohou vyzdvihnout estetiku díla, nebo jasněji komunikují požadované sdělení.",
      ],
      6: [
        "Většina z nás je poháněna vnější inspirací. Máte nějakou inspiraci? Je někdo nebo něco, koho obdivujete a chcete jít v jeho stopách? Možná budete chtít dokončit své umělecké dílo ve stylu…",
      ],
    },
    sculpture: {
      lookup: [
        "sculpture_types_CZ",
        "sculpture_content_CZ",
        "sculpture_forms_CZ",
        "emotions_CZ",
        "structure_looks_CZ",
        "sculpture_art_styles_CZ",
      ],
      1: [
        "Buďme konkrétnější. Pracujete s prostorem a hmotou, formujete ji do požadované struktury a tvaru. Mám po ruce široký výběr možných cest, stačí si jen vybrat!",
      ],
      2: [
        "Začněme přemýšlet o obsahu a uspořádání. Myslete na věci, postavy - opravdu cokoli.",
      ],
      3: [
        "Sochy jsou prostorové objekty, které pracují s prostředím kolem sebe. Způsob, jakým pracují, aby splývaly nebo vyčnívaly, se projeví úplně jiným vnímáním díla!",
      ],
      4: [
        "Teď, když víme, co je v díle, potřebujeme také vědět, jak to bude vyobrazeno. Přemýšlejte o emocích a energiích, které byste chtěli svým dílem zprostředkovat!",
      ],
      5: [
        "Ve světě umění existuje nepřeberné množství stylů - ty buď pomohou vyzdvihnout estetiku díla, nebo jasněji komunikují požadované sdělení.",
      ],
      6: [
        "Většina z nás je poháněna vnější inspirací. Máte nějakou inspiraci? Je někdo nebo něco, koho obdivujete a chcete jít v jeho stopách? Možná budete chtít dokončit své umělecké dílo ve stylu…",
      ],
    },
    photography: {
      lookup: [
        "photo_content_CZ",
        "photo_setting_CZ",
        "camera_angles_CZ",
        "camera_settings_CZ",
        "lighting_CZ",
        "emotions_CZ",
      ],
      1: [
        "Začněme přemýšlet o obsahu a uspořádání. Myslete na věci, postavy - opravdu cokoli.",
      ],
      2: ["Víme, na co se zaměřujeme, ale co všechno kolem?"],
      3: [
        "Fotografie je především o perspektivě. Představte si sami sebe ve vztahu k objektu/subjektu a odkud ho zachycujete!",
      ],
      4: [
        "Každý fotoaparát má nastavení, se kterými lze manipulovat. To vše drasticky změní konečný výsledek naší fotografie!",
      ],
      5: [
        "Osvětlení je klíčovou součástí fotografie! Všechny fotky se tvoří odraženým světlem procházejícím čočkou fotoaparátu.",
      ],
      6: [
        "Přemýšlejte o emocích a energiích, které byste chtěli svým dílem zprostředkovat!",
      ],
    },
  },
  DE: {
    medium:
      "Die erste Entscheidung, die jeder Künstler treffen muss, ist die Wahl des Mediums: Was für ein Kunstwerk soll es werden? Jede Auswahl hat ihre eigenen Besonderheiten und führt Sie auf einen etwas anderen kreativen Weg. Welche davon ist Ihre Berufung?",
    painting: {
      //lookup holds the hint cloud variable for each stage ordered by stage id
      lookup: [
        "painting_types_DE",
        "painting_content_DE",
        "painting_setting_DE",
        "emotions_DE",
        "looks_techniques_DE",
        "painting_art_styles_DE",
      ],
      //holds the guiding prompt for each dialogue stage named by stage id (such that it can be called as prompt[stage])
      1: [
        "Lasst uns genauer werden. Es gibt unendlich viele Möglichkeiten, was man auf einer Leinwand machen kann. Jede Form hat ihre Magie und alle stehen Ihnen zur Verfügung. Nun, welches wird es sein?",
      ],
      2: [
        "Sobald wir wissen, wie wir uns dem Kunstwerk nähern, können wir damit beginnen, es auszufüllen. Denken Sie an Dinge, Charaktere – wirklich alles.",
      ],
      3: [
        "Wir wissen, worauf wir uns konzentrieren, aber was ist mit allem drumherum. Wo spielt diese Szene? Gibt es überhaupt eine Einstellung?",
      ],
      4: [
        "Nun, da wir wissen, was auf dem Kunstwerk zu sehen ist, müssen wir auch wissen, wie es dargestellt wird. Denken Sie an Emotionen und Energien, die Sie durch Ihr Kunstwerk vermitteln möchten!",
      ],
      5: [
        "Wir kommen näher. Es gibt unzählige Stile in der Welt der Kunst – diese helfen entweder, die Visualität Ihrer Szene hervorzuheben oder die gewünschte Botschaft besser zu kommunizieren.",
      ],
      6: [
        "Die meisten von uns werden von äußerer Inspiration getrieben, die oft in einer Person oder Gruppe Gestalt annimmt. Haben Sie eine Inspiration? Vielleicht möchten Sie Ihr Kunstwerk im Stil von …",
      ],
    },
    sculpture: {
      lookup: [
        "sculpture_types_DE",
        "sculpture_content_DE",
        "sculpture_forms_DE",
        "emotions_DE",
        "structure_looks_DE",
        "sculpture_art_styles_DE",
      ],
      1: [
        "Lasst uns genauer werden. Sie arbeiten mit Raum und Materie und formen sie in eine gewünschte Struktur und Form. Ich habe eine breite Auswahl an möglichen Wegen zur Hand, Sie müssen sich nur für einen entscheiden!",
      ],
      2: ["Denken Sie an Dinge, Charaktere - wirklich alles. "],
      3: [
        "Skulpturen sind physische 3D-Objekte, die mit dem Raum um sie herum arbeiten. Die Art und Weise, wie sie sich einfügen oder abheben, führt zu einer völlig anderen Lesart der Skulptur!",
      ],
      4: [
        "Nun, da wir wissen, was in dem Kunstwerk steckt, welche Form es haben wird, müssen wir auch wissen, welche Art von Energie diese Skulptur ausstrahlen wird.",
      ],
      5: [
        "Wir kommen näher. Es gibt unzählige Stile in der Welt der Kunst – diese helfen entweder, die Visualität Ihrer Szene hervorzuheben oder die gewünschte Botschaft besser zu kommunizieren.",
      ],
      6: [
        "Die meisten von uns werden von äußerer Inspiration getrieben, die oft in einer Person oder Gruppe Gestalt annimmt. Haben Sie eine Inspiration? Vielleicht möchten Sie Ihr Kunstwerk im Stil von …",
      ],
    },
    photography: {
      lookup: [
        "photo_content_DE",
        "photo_setting_DE",
        "camera_angles_DE",
        "camera_settings_DE",
        "lighting_DE",
        "emotions_DE",
      ],
      1: [
        "Beginnen wir mit dem Nachdenken über den Inhalt und die Anordnung. Denken Sie an Dinge, Charaktere - wirklich alles.",
      ],
      2: [
        "Wir wissen, worauf wir uns konzentrieren, aber was ist mit allem drumherum. Wo spielt diese Szene? Gibt es überhaupt eine Einstellung?",
      ],
      3: [
        "Beim Fotografieren dreht sich alles um die Perspektive. Stell dir dich in Relation zum Objekt vor!",
      ],
      4: [
        "Jede Kamera hat einige Einstellungen, die manipuliert werden können. All dies wird das Endergebnis unseres Fotos drastisch verändern!",
      ],
      5: [
        "Die Beleuchtung ist ein entscheidender Teil der Fotografie, da alle fotografischen Funktionen auf das reflektierte Licht, das auf das Objektiv der Kamera trifft, basieren.",
      ],
      6: [
        "Nun, da wir wissen, was auf dem Kunstwerk zu sehen ist, müssen wir auch wissen, wie es dargestellt wird. Denken Sie an Emotionen und Energien, die Sie durch Ihr Kunstwerk vermitteln möchten!",
      ],
    },
  },
};

module.exports = { Facts, Prompts };
